package com.wavetransakt.wallet.funding;

public enum FundingReconciliationReasonCode {
    UNMATCHED_FUNDING_ACCOUNT,
    IDENTIFIER_CONFLICT,
    PROVIDER_FINALITY_UNCONFIRMED,
    PROVIDER_SETTLEMENT_UNCONFIGURED,
    PROVIDER_STATUS_UNRESOLVED,
    AMOUNT_OR_CURRENCY_MISMATCH,
    DUPLICATE_SUSPECTED,
    MANUAL_REVIEW_REQUIRED
}
