ALTER TABLE users
    ADD COLUMN IF NOT EXISTS bvn_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS nin_verified BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS government_identity_verified_at TIMESTAMP NULL;
